version: "3"

services:
  cli:
    environment:
      - PATH="$PATH:$HOME/.cargo/env"
    image: csegarragonz/rust-book:${RUST_BOOK_VERSION}
    stdin_open: true
    tty: true
    volumes:
      - ./:/rust-book
